import Head from 'next/head';
import { Header } from "./Header";
import { Footer } from "./Footer";

export const Layout = ({children}) => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <main className='container mx-auto mt-14'>
                { children }
            </main>
            <Footer />
        </>
    );
}